---
apiVersion: v1
kind: Service
metadata:
  name: voting-app-service
  labels:
    author: grace
    name: voting-app-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    author: grace
    name: voting-app-pod
...
