---
apiVersion: v1
kind: Pod
metadata:
  name: worker-app-pod
  labels:
    author: grace
    name: worker-app-pod
spec:
  containers:
    name: worker-app
    image: dockersamples/examplevotingapp_worker
...